echo "We are trying this practical from linux EC2"
echo "I am from Young minds"
echo "We are from batch-27" 
echo "I am learning Git/Github"
echo "I have added new code"
echo "I m learning branching in git"
echo "Adding one more line to test git pull"
echo "Final line added to test git fetch"
echo "This line is added from GitHub website directly"
echo "This line is added from local system after cloning"
echo "This line is added to test git stash"
echo "This line is added after applying stash"
echo "This line is added to test git rebase"
echo "This line is added to test git cherry-pick"